/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PulumiButton {
    }
}
declare global {
    interface HTMLPulumiButtonElement extends Components.PulumiButton, HTMLStencilElement {
    }
    var HTMLPulumiButtonElement: {
        prototype: HTMLPulumiButtonElement;
        new (): HTMLPulumiButtonElement;
    };
    interface HTMLElementTagNameMap {
        "pulumi-button": HTMLPulumiButtonElement;
    }
}
declare namespace LocalJSX {
    interface PulumiButton {
    }
    interface IntrinsicElements {
        "pulumi-button": PulumiButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pulumi-button": LocalJSX.PulumiButton & JSXBase.HTMLAttributes<HTMLPulumiButtonElement>;
        }
    }
}
