name: Publish
on:
    workflow_dispatch:

jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - uses: actions/setup-node@v2
              with:
                  node-version: "14.x"
                  registry-url: "https://registry.npmjs.org"

            - name: Set Git User
              run: |
                  git config --global user.name "${{ github.actor }}"
                  git config --global user.email "${{ github.actor }}@users.noreply.github.com"

            - name: Build and Publish ✨
              run: make ensure build publish
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
                  PULUMI_STACK_NAME: pulumi/dev
